### ISSUE TITLE
Minimum Cluster Size Broken

### ISSUE THREAD

**Issue by jmsunseri** [infusion-code/angular-maps#77]
I specified `<x-cluster-layer [GridSize]="50" [ClusteringEnabled]="true" [UseDynamicSizeMarkers]="true" [DynamicMarkerBaseSize]="18" [DynamicMarkerRanges]="ranges" [MinimumClusterSize]="4">` in my html but still I get clusters of 3 or 2.  In my data sometimes I have several points with the exact same lat long and  zooming into the lowest level and still only being able to see a cluster marker instead of the points won't work.

**Comment by thor-schueler** [comment]
@jmsunseri , can you say whether you are using bing or google? The clustering behavior is different for each and as a result, some of the parameters are specific to either the google or bing implementation. We tried to minimize those implementation specific parameters but could not quire eliminate them.

The ```MinimumClusterSize``` parameter is only applicable in google currently. So if you are using bing, the only control you have over the clusters is the ```GridSize``` (https://msdn.microsoft.com/en-us/library/mt712813.aspx). Now, Microsoft will take input, so if there is a compelling reason for why Bing maps should allow a minimum cluster size, they might add that to the backlog and product. You can request that over at the bingmaps repo (https://github.com/Microsoft/BingMapsV8CodeSamples) @rbrundritt for awareness....

**Comment by thor-schueler** [comment]
@jmsunseri : one possibility (if you use bing) would be to use the cluster click action to expand the cluster by disabling clustering (or disable clustering at a certain zoom level). Check the spider cluster action to see how to go about expanding a cluster on click. If your lat longs are the same for certain entities, you might have to do that anyway, otherwise, on the map, the pins for your entities will just overlay each other, even without clustering....

**Comment by jmsunseri** [comment]
I'm no longer employed by the company that was paying me to work on this
project and don't have access to the code any longer. I was using bing maps
though.  If I ever get into this again I'll have to try your suggestion.

Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.
